- name: Get an existing Service object
  kubernetes.core.k8s_info:
    api_version: v1
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    kind: DaemonSet
    name: "{{ sro_ds }}"
    namespace: "{{ sro_ds_ns }}"
  register: sro_ds_backup
- local_action:
    module: copy
    content: "{{ sro_ds_backup }}"
    dest: sro_ds_backup.yaml
