- name: Individual tasks for each node
  block:
  - name: Install pre-requisites modules
    pip:
      name:
        - openshift
        - pyyaml
        - kubernetes
  - name: Upload local KUBECONFIG
    include_tasks: upload_local_kubeconfig.yaml

  - name: Login to OCP cluster and get API KEY
    include_tasks: ocplogin.yaml

  - name: Cordon and drain
    include_tasks: drain.yaml

  - name: Delete old SRO Pods
    include_tasks: delete_sro_pods.yaml

  - name: Reboot node
    include_tasks: rebootnode.yaml

  - name: Uncordon
    include_tasks: uncordon.yaml
